[client]
showSidebarNavigation = false

[theme]
base                     = "dark"
primaryColor             = "#cc2222"
backgroundColor          = "#0a0a0a"
secondaryBackgroundColor = "#111111"
textColor                = "#f5f5f5"
font                     = "monospace"

[server]
runOnSave = true
